# Generated by Django 5.1.3 on 2024-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=50)),
                ('a_length', models.IntegerField(blank=True)),
                ('a_width', models.IntegerField(blank=True)),
                ('a_depth', models.IntegerField(blank=True)),
                ('a_weight', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('backpack_name', models.CharField(max_length=50)),
                ('b_length', models.IntegerField(blank=True)),
                ('b_width', models.IntegerField(blank=True)),
                ('b_depth', models.IntegerField(blank=True)),
                ('b_weight', models.IntegerField(blank=True)),
            ],
        ),
    ]
