# Generated by Django 5.1.3 on 2024-11-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_airline_airline_airline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='a_depth',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airline',
            name='a_length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airline',
            name='a_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airline',
            name='a_width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='b_depth',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='b_length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='b_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='b_width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
